#
# Makefile for industrial I/O gyroscope sensor drivers
#

obj-$(CONFIG_ADIS16136) += adis16136.o
obj-$(CONFIG_HID_SENSOR_GYRO_3D) += hid-sensor-gyro-3d.o
obj-$(CONFIG_SENSORS_L3G4200D)  += l3g4200d.o
